name: login_2
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
  otp_text_field: ^1.1.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  get: ^4.6.5
  image_picker: ^1.0.1
  shared_preferences: ^2.2.0
  flutter_widget_from_html: 0.10.3
  loading_indicator: ^3.1.1
  fluttertoast: ^8.2.2
  # flutter_widget_from_html: ^0.6.0
  # webview_flutter: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
